context:
  name: rocm-core
  version: "7.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocm-core/archive/refs/tags/rocm-${{ version }}.tar.gz"
    sha256: 3c7e990ff4da60119c8575982660331bf636f63a9c68c6a344d410b2bdfa5d39

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
    script:
      - cmake-package-check rocm-core
  - package_contents:
      include:
        - rocm-core/rocm_version.h
      lib:
        - rocm-core

about:
  homepage: https://github.com/ROCm/rocm-core
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: "ROCm core package"

extra:
  recipe-maintainers:
    - traversaro
    - isuruf
